{% set name = "opentelemetry-exporter-jaeger" %}
{% set version = "1.6.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry-exporter-jaeger-{{ version }}.tar.gz
  sha256: fb58beb31e18383563dceb1e20f946915812d2aa88b32612b2c48b2dfc58c850

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - opentelemetry-exporter-jaeger-proto-grpc ==1.6.1
    - opentelemetry-exporter-jaeger-thrift ==1.6.1
    - python >=3.6

test:
  imports:
    - src
    - src.opentelemetry
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python/tree/main/exporter/opentelemetry-exporter-jaeger
  summary: Jaeger Exporters for OpenTelemetry
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
